source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

# GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Performance
gem "webrick"
